---
- name: Get username
  become: false
  shell:
    cmd: whoami
  register: user

- name: Set home username
  set_fact:
    username: "{{ user.stdout }}"

- name: show username
  become: false
  debug: var=username

- name: Deploy application
  copy:
    src: "/home/{{ username }}/{{ app_destination }}/dist"
    dest: "{{ prod_destination }}"
    directory_mode: true
...
